# For IPMV
echo start process!
set -x # -e stop when any code raise error; -x print command
start_time=$(date +%s)

#8.17 TAD-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B
#python main_DualVisEncoder.py --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B
#python main_DualVisEncoder.py --seed 228 --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B_seed3407
#
#python main_DualVisEncoder.py --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B-noCaption-yz
#python main_DualVisEncoder.py --seed 228 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B-noCaption_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold50-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold50-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold50-CLIP-B-noCaption_seed3407

#python main_DualVisEncoder.py --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/ucf-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp  --exp-name UCF-videoMAE-videoMaeST-CLIP-B
#python main_DualVisEncoder.py --seed 228 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/ucf-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-CLIP-B_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/ucf-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-CLIP-B_seed3407

#8.13
#python main_DualVisEncoder.py --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption-yz
#python main_DualVisEncoder.py --dataset TAD --batch-size 64 --feature-group vis --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption
#python main_DualVisEncoder.py --seed 228 --dataset ucf --batch-size 64 --feature-group vis --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset ucf --batch-size 64 --feature-group vis --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption_seed3407
#python main_DualVisEncoder.py --seed 228 --dataset TAD --batch-size 64 --feature-group vis --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset TAD --batch-size 64 --feature-group vis --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --copy2SSD_path /home/cw/tmp --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B-noCaption_seed3407

#python main.py --dataset violence --feature-group both --fusion add --aggregate_text --extra_loss --feature-size 1024 --exp-name XD-i3d-official

#videoMAE-ST-SepPooling+CLIPB-concat 7.30
#python main_DualVisEncoder.py --dataset TAD --batch-size 64  --feature-group both --fusion concat       --feat-extractor videomae --feature-size 768       --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list       --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list       --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip       --use_dic_gt --aggregate_text --extra_loss       --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B
#python main_DualVisEncoder.py --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B
#python main_DualVisEncoder.py --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/ucf-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name UCF-videoMAE-videoMaeST-CLIP-B

#python main_DualVisEncoder.py --seed 228 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset ucf --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/ucf-videoMae-UCF_FBseparation_threthold10-videoMAE-ST.list --test-rgb-list list/ucf-videoMae-test-UCF_FBseparation_threthold10-videoMAE-ST.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/Crime/UCF_ten_crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name UCF-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B_seed3407
#python main_DualVisEncoder.py --seed 228 --dataset TAD --batch-size 64  --feature-group both --fusion concat       --feat-extractor videomae --feature-size 768       --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list       --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list       --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip       --use_dic_gt --aggregate_text --extra_loss       --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset TAD --batch-size 64  --feature-group both --fusion concat       --feat-extractor videomae --feature-size 768       --rgb-list list/TAD-videoMae-FBseparation_threthold10-videoMAE-ST.list       --test-rgb-list list/TAD-videoMae-test-FBseparation_threthold10-videoMAE-ST.list       --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip       --use_dic_gt --aggregate_text --extra_loss       --exp-name TAD-videoMAE-videoMaeST-FBseparation_threthold10-CLIP-B_seed3407

# videoMAE-ST+CLIPB-concat 7.30
#python main_DualVisEncoder.py --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/TAD-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name TAD-videoMAE-videoMaeST-CLIP-B
#python main_DualVisEncoder.py --seed 228 --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/TAD-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name TAD-videoMAE-videoMaeST-CLIP-B_seed228
#python main_DualVisEncoder.py --seed 3407 --dataset TAD --batch-size 64 --feature-group both --fusion concat --feat-extractor videomae --feature-size 768 --rgb-list list/TAD-videoMae-finetune_pretrain_with_RandomMaskinK400-100_457.list --test-rgb-list list/TAD-videoMae-test-finetune_pretrain_with_RandomMaskinK400-100_457.list --feat-extractor-B clip --feature-size-B 512 --vis_feature_path_B_folder /media/cw/584485FC4485DD5E/csh/tevad-pro/save/TAD/TAD_10crop_clip --use_dic_gt --aggregate_text --extra_loss --exp-name TAD-videoMAE-videoMaeST-CLIP-B_seed3407

end_time=$(date +%s)
runtime_hours=$(((end_time - start_time)/3600))
echo "任务运行时间：$runtime_hours 小时"
date +"%Y-%m-%d %H:%M:%S"